In [8]:
import s3fs
import h5py
import numpy as np

In [9]:
file = "s3://ghrc-fcx-field-campaigns-szg/Olympex/instrument-raw-data/cpl/olympex_radex_CPL_ATB_16915_20151109.hdf5"
date = file.split("_")[5].split(".")[0]
base_time = np.datetime64('{}-{}-{}'.format(date[:4], date[4:6], date[6:]))

In [14]:
fs = s3fs.S3FileSystem(anon=False)
with fs.open(file) as cplfile:
    with h5py.File(cplfile, 'r') as f1:
        
        # atb1064 = f1['ATB_1064'][()]
        # AltBin = f1['Bin_Alt'][()] * 1000    #[km] ==> [m]
        
        atb = f1['ATB_1064'][()]
        rad_range = f1['Bin_Alt'][()] * 1000    #[km] ==> [m]
        
        # print(ref)
        
        # lon  = f1['Longitude'][()]
        # lat  = f1['Latitude'][()]
        # alt  = f1['Plane_Alt'][()] * 1000   #[km] ==> [m]
        # roll = f1['Plane_Roll'][()] * to_rad
        # head = f1['Plane_Heading'][()] * to_rad
        # pitch = f1['Plane_Pitch'][()] * to_rad
        
        # delta = [h*3600+m*60+s for (h,m,s) in 
        #         zip(f1['Hour'][()], f1['Minute'][()], f1['Second'][()])]
        
        delta = [(base_time + (h*3600+m*60+s).astype('timedelta64[s]')) for (h,m,s) in 
        zip(f1['Hour'][()], f1['Minute'][()], f1['Second'][()])] #delta is in seconds
        
        # print(delta)

num_col = atb.shape[0] # number of cols, say 7903
num_row = atb.shape[1] # number of rows, say 757

print(num_row, " x ", num_col)

900  x  5401


In [26]:
atb

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         2.49735646e-04, -1.27640556e-03, -1.21987316e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         4.13517079e-04,  5.29100769e-04, -1.73292544e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         5.82839075e-04, -1.56349539e-03, -2.59784148e-03],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -6.10993539e-05, -1.01486919e-03, -2.10252353e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.01251731e-03,  3.43705805e-04,  1.11119620e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.00433087e-03,  2.53349698e-04, -6.79996723e-04]])

In [17]:
atb.shape


(5401, 900)

In [18]:
atb.flatten().shape

(4860900,)

In [19]:
5401 * 900

4860900

In [20]:
atb

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         2.49735646e-04, -1.27640556e-03, -1.21987316e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         4.13517079e-04,  5.29100769e-04, -1.73292544e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         5.82839075e-04, -1.56349539e-03, -2.59784148e-03],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -6.10993539e-05, -1.01486919e-03, -2.10252353e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.01251731e-03,  3.43705805e-04,  1.11119620e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.00433087e-03,  2.53349698e-04, -6.79996723e-04]])

In [22]:
fatb = atb.flatten()


In [23]:
fatb[10000: 1000001]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
       3.52801878e-06, 3.18282994e-06, 4.53155637e-06])

In [27]:
fatb.min()

-0.01644991051878615

In [28]:
fatb.max()

2.6162068566496197