In [5]:
import s3fs
import h5py
import numpy as np

In [6]:
file = "s3://ghrc-fcx-field-campaigns-szg/Olympex/instrument-raw-data/cpl/olympex_radex_CPL_ATB_16915_20151109.hdf5"
date = file.split("_")[5].split(".")[0]
base_time = np.datetime64('{}-{}-{}'.format(date[:4], date[4:6], date[6:]))

In [7]:
fs = s3fs.S3FileSystem(anon=False)
with fs.open(file) as cplfile:
    with h5py.File(cplfile, 'r') as f1:
        
        # atb1064 = f1['ATB_1064'][()]
        # AltBin = f1['Bin_Alt'][()] * 1000    #[km] ==> [m]
        
        atb = f1['ATB_1064'][()]
        rad_range = f1['Bin_Alt'][()] * 1000    #[km] ==> [m]
        
        # print(ref)
        
        lon  = f1['Longitude'][()]
        lat  = f1['Latitude'][()]
        alt  = f1['Plane_Alt'][()] * 1000   #[km] ==> [m]
        # roll = f1['Plane_Roll'][()] * to_rad
        # head = f1['Plane_Heading'][()] * to_rad
        # pitch = f1['Plane_Pitch'][()] * to_rad
        
        # delta = [h*3600+m*60+s for (h,m,s) in 
        #         zip(f1['Hour'][()], f1['Minute'][()], f1['Second'][()])]
        
        delta = [(base_time + (h*3600+m*60+s).astype('timedelta64[s]')) for (h,m,s) in
            zip(f1['Hour'][()], f1['Minute'][()], f1['Second'][()])] #delta is in seconds
        
        # print(delta)

num_row = atb.shape[0] # number of rows, say 757
num_col = atb.shape[1] # number of cols, say 7903

print(num_row, " x ", num_col)

5401  x  900


### ROUGH

In [30]:
atb.shape

(5401, 900)

In [31]:
print(type(alt))
alt.shape

<class 'numpy.ndarray'>


(5401,)

In [32]:
print(type(delta))
len(delta)

<class 'list'>


5401

What does repeat does???

In [35]:
lon1 = np.repeat(lon, num_row)
print(type(lon1))
lon1.shape

<class 'numpy.ndarray'>


(4860900,)

In [39]:
np.repeat([1,2], 100)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

What does Stack does???

In [55]:
a = [1,2,3]
b = ["a", "b", "c"]
c = ["x", "y", "z"]

stck0 = np.stack([a, b, c])
stck0

array([['1', '2', '3'],
       ['a', 'b', 'c'],
       ['x', 'y', 'z']], dtype='<U21')

In [62]:
stck1 = np.stack([a,b,c], axis=0)
stck1

array([['1', '2', '3'],
       ['a', 'b', 'c'],
       ['x', 'y', 'z']], dtype='<U21')

In [61]:
stck2 = np.stack([a,b,c], axis=1)
stck2

array([['1', 'a', 'x'],
       ['2', 'b', 'y'],
       ['3', 'c', 'z']], dtype='<U21')

In [63]:
stck3 = np.stack([a,b,c], axis=-1)
stck3

array([['1', 'a', 'x'],
       ['2', 'b', 'y'],
       ['3', 'c', 'z']], dtype='<U21')

In [64]:
# VS NORMAL ARRAY OF ARRAY FORMARTION
stck4 = [a,b,c]
stck4

[[1, 2, 3], ['a', 'b', 'c'], ['x', 'y', 'z']]

STACK gives cool functionality of adding adjacent element of an array in a COOL way!

What does APPEND in np does?

In [68]:
t = [1,2,3,4,5,6,7,8,9]
t1 = ['a', 'b','c','d','e','f','g', 'h', 'i'] 
n_t = []
n_t = np.append(n_t, t)
print(n_t)
n_t = np.append(n_t, t1)
n_t


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


array(['1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', 'a',
       'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U32')

APPEND in np, appends!! converting all the elements in array in np dtype

In [80]:
a1 = np.array([1,2,3,4,5])
a1 = (a1 - 1)
a1

array([0, 1, 2, 3, 4])

### more expolration of data

In [26]:
atb

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         2.49735646e-04, -1.27640556e-03, -1.21987316e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         4.13517079e-04,  5.29100769e-04, -1.73292544e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         5.82839075e-04, -1.56349539e-03, -2.59784148e-03],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -6.10993539e-05, -1.01486919e-03, -2.10252353e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.01251731e-03,  3.43705805e-04,  1.11119620e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.00433087e-03,  2.53349698e-04, -6.79996723e-04]])

In [17]:
atb.shape


(5401, 900)

In [18]:
atb.flatten().shape

(4860900,)

In [19]:
5401 * 900

4860900

In [20]:
atb

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         2.49735646e-04, -1.27640556e-03, -1.21987316e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         4.13517079e-04,  5.29100769e-04, -1.73292544e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         5.82839075e-04, -1.56349539e-03, -2.59784148e-03],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -6.10993539e-05, -1.01486919e-03, -2.10252353e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.01251731e-03,  3.43705805e-04,  1.11119620e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.00433087e-03,  2.53349698e-04, -6.79996723e-04]])

In [22]:
fatb = atb.flatten()


In [23]:
fatb[10000: 1000001]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
       3.52801878e-06, 3.18282994e-06, 4.53155637e-06])

In [27]:
fatb.min()

-0.01644991051878615

In [28]:
fatb.max()

2.6162068566496197

VERDICT

In [1]:
# num_cols = atb.shape[1] # number of cols
# # shape gives, (r,c) which  is number of rows and number of cols 

# lon = np.repeat(lon, num_cols)
# lat = np.repeat(lat, num_cols)
# alt = np.repeat(alt, num_cols)

# atb = atb.flatten()

Each of the data has same number of data. i.e. lat, lon, alt, atb all has same amount of data say 'n'

There something more about atb. atb has n data, but each n data has further 5 data (say).
It infers that atb data is actually a 2d dataset.

So, inorder to represent each data elements of the atb uniquely:
first spread all the 2d data into a single dimensional array

Doing this will generate 5 unqiue for each ith atb data.
hence, the total atb data length after spread will be n*5.

In addition, we will need to mainain the shape of the others data vars as well.


So, we need to do it spread each ith element of other data vars by 5 (say) as well. Use np.repeat(lon, 5)